### ISSUE TITLE
Live tracking

### ISSUE THREAD

**Issue by vicb** [vicb/flyxc#61]
## Server side

- [x] Update DB to allow multiple devices
- [x] Merge fixes from multiple devices 
- [x] Support incremental updates (instead of fetching 24h)

## Client side

- [x] Support full and incremental updates (24 & 2h)
- [x] Generate geojson from proto
- [x] Support 3d
- [ ] Add InReach status - see #23
- [x] Validate device address / id - see #29

## Misc

App/Platform in progress:
- FlyMaster - no public API
  - https://github.com/FAI-CIVL/FAI-Airscore/blob/313c8f6b20716c685db66d67fe57f70e986d2325/airscore/core/livetracking.py
  - http://wiki.fai.org/download/attachments/35651593/Flymaster+usage+notes+v1.pdf
  - `https://lt.flymaster.net/wlb/getLiveData.php?trackers={%22214852%22:1613411183}`
  - `https://wlb.flymaster.net/get_active_trackers.php?json`
  - https://livetrack360.com/livetracking/2d/1?

App/Platform discussions:
- XCTrack - they are working on a public API
- Syride - they are working on a public API

App/Plaform supported:
- Skylines
- XCGlobe / Flyme

App/Platform closed
- livetrack24 - no answers

**Comment by BarryPSmith** [comment]
The tracking feature is nice, but if there are multiple pilots in the same area it can be difficult to select and distinguish between the different tracks, particularly on mobile.

Would you consider making a list of pilots that are visible in the current viewport, and either allow the user to click a pilot's name and highlight their track (much like clicking on their track on the map does), or give pilots checkboxes so that you can choose to hide some of them?

**Comment by vicb** [comment]
Hiding pilots: that's a no because of safety. 

To select a pilot/track you can click on "Live tracks" in the menu, it will display a list of pilots. By default the list is order by distance from the center of the viewport (There is an option to sort the list by time in the header bar if you prefer)

![image](https://user-images.githubusercontent.com/248818/117193465-be576e80-ad97-11eb-9a67-318f61b9b74c.png)

That sounds like what you are asking for ?

**Comment by BarryPSmith** [comment]
Oh yeah, thanks. Boy I can be blind sometimes...

**Comment by vicb** [comment]
No problem...
I plan to add some docs at some point (actually waiting for a fix in one of the library I use to do that).

**Comment by elgandoz** [comment]
@vicb XContest Live tracking should finally open up soon. If you're a dev with specific use case, they're open to release the API early (requires a token "manually" generated):

> This API (we call it Livedata API) is basically prepared. We only need to finish UI for auth token generation to make it available to all indiviual users.
In the meantime, in case you like to use it in your app, which would aggregate data of more users, you can contact us on [xctrack@xcontest.org](mailto:xctrack@xcontest.org) with your request. Please provide description of your livedata API use case to discuss possibilities and limitations of the API use.
Source: https://gitlab.com/xcontest-public/xctrack-public/-/issues/109#note_1532322275

If possible, please consider contacting the dev team, it would allow to dramatically increase the number of user available to track.

**Comment by vicb** [comment]
Thanks for the info @elgandoz 

I'm contact with them. They first told that the API would be ready soon in Apr 2022 and then again in Apr 2023 :)
Great to hear that things are moving.

I have an update in mind for when there are pilots close-by: clicking on the "gaggle" would "explode" the view to better track where each of them are. I definitely prefer that to the XContest way to group pilots by default. This and the other few high priority stuff should hopefully be ready in a couple months.

Then I'll think about integrating their API.

**Comment by vicb** [comment]
@elgandoz thanks for your message... it was simple so I did it today, check the LT setup.

**Comment by elgandoz** [comment]
Thank you so much for your prompt work @vicb, I added my UUID and it was all fairly simple.
I believe this is the first service to provide XContest compatibility, with all the other providers available, this is the best aggregator out there. I will spread the word around, thanks again

**Comment by vicb** [comment]
> I will spread the word around, thanks again

Please wait a couple days before doing that.
I just want to make sure it works with a few early adopters before spreading the word.
Thanks

**Comment by elgandoz** [comment]
I will hopefully flying this weekend, with few providers enabled (SkyLines, InReach and now XContest), I will report if I find any issues

**Comment by elgandoz** [comment]
Sorry to keep adding stuff on this closed ticket, but there is a yet another new tracking service for paragliders which is gaining traction (mostly in Spain for now):
https://volandoo.com/
It's simple with no frills but well done,  it provides a free tier with "regular" tracking. Most importantly the tracking app is available for both Android and iOS, which I believe no other tracking service offers directly.
It could be worth investigating if the public feed could be integrated with this platform.
